Added Manipulator Trigger
IronRiders/ChargedUp pull request #34
Opened 2023-01-27 03:00 UTC by Dar1ngit

This Pull Request closes issue #

Description of the changes:
 - 

 - [ ] I have labelled this issue with the priority and correct subsystem.
 - [ ] I set the person that I worked on this with as a reviewer (who will need to approve the changes)

2023-01-27 04:48 UTC, SBsteveyHops approved these changes
I do not see any problems with the code but it looks like the "Format" check failed again.

2023-01-27 06:29 UTC, LinusSkucas requested changes
Just 1 tiny thing

2023-01-27 06:29 UTC, LinusSkucas commented on src/main/java/frc/robot/RobotContainer.java
> +    new JoystickButton(controllerHID, 9).onTrue(new GrabManipulatorCommand(manipulator));
Could you stick this in the `configureBindings` method? Just to keep things clean.

2023-01-27 06:46 UTC, LinusSkucas commented
Closes #7

2023-01-27 07:01 UTC, AG-Coding requested changes

2023-01-27 16:20 UTC, SBsteveyHops approved these changes
I don't see any problems with the changes.

2023-01-31 00:03 UTC, LinusSkucas approved these changes

2023-01-31 00:09 UTC, AG-Coding approved these changes

2023-01-31 00:09 UTC, merged