Changed the Grab Manipulator Commands to allow for different Current …
IronRiders/ChargedUp pull request #48
Opened 2023-02-02 00:35 UTC by ryanelbert5125gmail

…Limits when grabing and releasing boxes and cones

This Pull Request closes issue #

Description of the changes:
 - 

 - [ ] I have labelled this issue with the priority and correct subsystem.
 - [ ] I set the person that I worked on this with as a reviewer (who will need to approve the changes)

2023-02-03 01:43 UTC, LinusSkucas commented on src/main/java/frc/robot/Constants.java
> +  public static final int MANIPULATOR_CURRENT_LIMIT_BOX = 10;
Let's make these more realistic, how about 20 for the cone and 15 for the cube.

2023-02-03 01:48 UTC, LinusSkucas requested changes

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/Constants.java
> +  public static final int MANIPULATOR_CURRENT_LIMIT_BOX = 10;
Let's make these more realistic, how about 20 for the cube and 15 for the cone

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/RobotContainer.java
> +        .onTrue(new ReleaseManipulatorCommand(manipulator, false)); // Button For Releasing Boxes
We don't need to differentiate how we release things.

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/commands/GrabManipulatorCommand.java
> +  public GrabManipulatorCommand(ManipulatorSubsystem manipulatorSubsystem, boolean coneGraber) {
Instead of a boolean can we use the enum?

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/commands/GrabManipulatorCommand.java
> +    if (coneGraber) {
Same thing; let's use the enum

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/commands/ReleaseManipulatorCommand.java
> +  public ReleaseManipulatorCommand(ManipulatorSubsystem manipulatorSubsystem, boolean grabcone) {
We shouldn't have to differentiate how we release things

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/subsystems/ManipulatorSubsystem.java
> +  public enum GrabObject {
This can go in its own file because we'll be referencing it a lot.

2023-02-03 01:48 UTC, LinusSkucas commented on src/main/java/frc/robot/Constants.java
>    public static final double MANIPULATOR_POWER = 1.0;
We can make it a bit more realistic
```suggestion
  public static final double MANIPULATOR_POWER = 0.8;
```

2023-02-03 03:02 UTC, ryanelbert5125gmail commented
We didn't know how to add the changes requested to this pull request so we were told by Anish to create another pull request

2023-02-03 04:04 UTC, LinusSkucas commented
You can commit them to this branch then push them. It'll update the pull request

2023-02-07 00:20 UTC, ryanelbert5125gmail commented
Committed revisions to branch

2023-02-08 22:34 UTC, LinusSkucas approved these changes

2023-02-08 22:34 UTC, merged