Removed bunch of useless comments and added drive
IronRiders/ChargedUp pull request #57
Opened 2023-02-08 08:08 UTC by AG-Coding

This Pull Request closes issue #

Description of the changes:
 - 

 - [ ] I have labelled this issue with the priority and correct subsystem.
 - [ ] I set the person that I worked on this with as a reviewer (who will need to approve the changes)

2023-02-08 22:33 UTC, Juliuscease123221 approved these changes

2023-02-08 22:54 UTC, SBsteveyHops approved these changes
Looks good, and I do not see any problems.

2023-02-08 23:50 UTC, SBsteveyHops submitted a review, later dismissed

2023-02-08 23:53 UTC, LinusSkucas requested changes

2023-02-08 23:53 UTC, LinusSkucas commented on src/main/java/frc/robot/Constants.java
> +  public static final double wheel_circumference = Units.inchesToMeters(DIAMETER * Math.PI);
ANISH WHAT IS THIS NAMING CONVENSION??????/?????//?>?>?>???

2023-02-08 23:53 UTC, LinusSkucas commented on src/main/java/frc/robot/Constants.java
> +  public static final double Gearing = 4;
it a variable, not no object

2023-02-08 23:53 UTC, LinusSkucas commented on src/main/java/frc/robot/subsystems/DriveSubsytem.java
> +  public void SetWheelSpeeds(MecanumDriveWheelSpeeds speed, boolean needPID) {
```suggestion
  public void setWheelSpeeds(MecanumDriveWheelSpeeds speed, boolean needPID) {
```

2023-02-08 23:53 UTC, LinusSkucas commented on src/main/java/frc/robot/RobotContainer.java
> +                drive.setChassisSpeeds(
Don't change the joystick input yet

2023-02-08 23:53 UTC, LinusSkucas commented on src/main/java/frc/robot/subsystems/DriveSubsytem.java
> +  private MecanumWheel[] motors = new MecanumWheel[4];
Do not use arrays.

2023-02-08 23:53 UTC, LinusSkucas commented on src/main/java/frc/robot/subsystems/DriveSubsytem.java
> +    motors[0] = new MecanumWheel(Constants.WHEEL_PORT_FRONT_LEFT, true);
Using arrays in confusing

2023-02-09 00:24 UTC, SBsteveyHops approved these changes

2023-02-09 00:43 UTC, LinusSkucas approved these changes

2023-02-09 00:46 UTC, SBsteveyHops approved these changes

2023-02-09 00:46 UTC, merged